名字: 【综合任务】
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '10 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/361183106/jjj.git ~/jjj
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/jjj
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json

      - name: '【书旗小说】'
        run: |
          cd ~/js   
          node Task/sqxs.js
 
