name: TT

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '10 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/361183106/chencc.git ~/chencc
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/chencc
          npm install
          npm install cron
          npm install request
      - name: '运行 【步步宝】'
        run: |
          cd ~/chencc   
          node Task/TT.js
